services:
  - type: web
    name: your-site-name
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2
    envVars:
      - key: PHP_VERSION
        value: 8.0